config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :supports
  get "/shows" => 'supports#shows', as: :shows
  root "supports#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/support.rb
class Support < ApplicationRecord




validates :name, presence: true
validates :email, presence:true

def self.search(keyword)
  where(["name ILIKE ? or message ILIKE ? or email ILIKE ? or department ILIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])


end
end


private

def self.recent_ten
  order(department: :desc).limit(10)
end
# select name, department.lenth

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/suports_controller.rb
class SuportsController < ApplicationController
  def index
    @suports = Support.new

  end

  def new

  end

  def create

  end

  def show

  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController

  before_action :find_params, only: [:show, :edit, :destroy, :update]

  def index
    @supports = Support.new

  end
def shows
  @supports2 = Support.search(params[:keyword])
@supports = @supports2.order(created_at: :desc).
                                  page(params[:page]).
                                  per(5)

end
  def new

  end

  def create
    @supports = Support.new supports_params

    if @supports.save
      redirect_to supports_path, notice:"post successfully created"
    else
      flash[:alert] = "please enter corect data "
      render :new
    end
  end

  def show
    @supports = Support.find find_params
  end

  def edit

  end

  def update
    if @supports.update supports_params
      redirect_to shows_path
            flash[:alert]= "masssage successfully edited"
    else
      flash[:alert]= "please enter correct data"
      render :edit
    end

  end

  def destroy
  @supports.destroy
      redirect_to shows_path
      flash[:alert]= "Messsage successfully deleted"
    end
 
private

      def find_params
          @supports = Support.find params[:id]
      end

      def supports_params
          params.require(:support).permit([:name, :email, :department, :message, :mark])
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/suports_helper.rb
module SuportsHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Starter Template for Bootstrap</title>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]> <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %> <![endif]-->

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>

        <div class="container">
            <div class="masthead">

                <div class="masthead">
                    <img class="img-responsive" src="http://www.air-it.co.uk/wp-content/uploads/2015/02/Service-Icons-04-320x320.png" alt="">
                    <div>

                        <div style="float: right">
                            <%= form_tag shows_path, :method => 'get' do %>
                            <p>
                                <%= text_field_tag :keyword, params[:keyword] %>
                                <%= submit_tag "Search", :name => nil %>
                            </p>
                            <% end %>
                        </div>

                        <h5>supporter</h5>
                        <nav>
                            <ul class="nav nav-justified">
                                <li class="active">
                                    <%= link_to "Home", supports_path %>
                                </li>
                                <li><%= link_to "Request List", shows_path %>
                                </li>

                            </ul>
                        </nav>
                    </div>
                </div>
                <hr>
                <div class="container">
                    <% flash.each do |name, msg| %>
                    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <%= msg %>
                    <% end %>
                    <% end %>
                    <%= yield %>
                </div>
            </div>
        </body>
    </html>

app/views/supports/_form.html.erb
<%= @supports.errors.full_messages.join(",") %>
<div style="padding-top:10px">
<%= form_for @supports, :html => { :class => "article-form" } do |x| %>
<div class="form-group padd">
<%= x.label :name, class:"col-sm-2 control-label" %>
 <div class="col-sm-10 padd">
<%= x.text_field :name, class:"form-control" %>
</div>
</div>
</br>
<div class="form-group padd ">
  <%= x.label :email, class:"col-sm-2 control-label" %>
   <div class="col-sm-10 padd">
  <%= x.text_field :email, class:"form-control", placeholder: "example@gmail.com"%>
</div>
</div>
<br>
  <div class="radio-inline padd">

    <%= x.radio_button :department, 'sales', :checked => true  %>
    <%= x.label :department_sales, 'Sales', class:"radio-inline radi"%>
    <%= x.radio_button :department, 'marketing'  %>
    <%= x.label :department_marketing, 'Marketing', class:"radio-inline radi"%>
    <%= x.radio_button :department, 'technical'%>
    <%= x.label :department_technical, 'Technical', class:"radio-inline radi"%>
  </div>
  <div class="form-group padd">
    <%= x.label :message, class:"col-sm-2 control-label" %>
     <div class="col-sm-10 padd">
    <%= x.text_area :message, class:"form-control" %>
  </div>
</div>
    <div class="padd">
       <%= x.submit "save", class:"btn btn-danger btn-lg" %>
    </div>

    <% end %>
  </form>
</div>

app/views/supports/_form2.html.erb
<div class="container">
<%= form_for @supports do |x| %>
<div>
<%= x.label :name %>
<%= x.text_field :name %>
</div>
<div>
  <%= x.label :email %>
  <%= x.text_field :email, placeholder: "example@gmail.com"%>

</div>
  <div>
    <%= x.radio_button :department, 'sales', :checked => true  %>
    <%= x.label :department_sales, 'Sales'%>
    <%= x.radio_button :department, 'marketing'  %>
    <%= x.label :department_marketing, 'Marketing'%>
    <%= x.radio_button :department, 'technical'%>
    <%= x.label :department_technical, 'Technical'%>
  </div>
  <div>
    <%= x.label :message %>
    <%= x.text_area :message %>
  </div>
  <div>
    <%= x.radio_button :mark, 'undone'%>
    <%= x.label :mark_undone, 'Undone'%>
  <%= x.radio_button :mark, 'done'  %>
  <%= x.label :mark_done, 'Done'%>
</div>
    <div>
       <%= x.submit "save" %>
    </div>

    <% end %>
  </form>
</div>

app/views/supports/edit.html.erb
<%= render 'form2' %>

app/views/supports/index.html.erb
<%= render "form" %>

app/views/supports/new.html.erb
<%= render "form" %>

app/views/supports/show.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
  <th>Name</th>
  <th>Email</th>
  <th>Department</th>
  <th>Message</th>
  <th>Action</th>
  </tr
></thead>

<tbody>
<tr>
  <td><%= @supports.name %></td>
  <td><%= @supports.email %></td>
  <td><%= @supports.department %></td>
  <td><%= @supports.message %></td>
  <td> <%= link_to "Edit", edit_support_path(@supports.id),{class: "btn btn-info btn-lg"} %>
</td>
</tr>
</tbody>
</table>

app/views/supports/shows.html.erb
<h1>Support Requests</h1>


<div>
<%= form_tag shows_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :keyword, params[:keyword] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

</div>

<hr>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
  <th>Name</th>
  <th>Email</th>
  <th>Department</th>
  <th>Message</th>
  <th>Action</th>
  </tr
></thead>
  <% @supports.each do |x| %>
<tbody>

<tr>
  <td><%= x.name %></td>
  <td><%= x.email %></td>
  <td><%= x.department %></td>
  <td><%= x.message %></td>
  <td> <%= link_to "edit", support_path(x.id),{class: "btn btn-info btn-lg"} %>
  <%= link_to "Delete", support_path(x.id),
                                    class: "btn btn-info btn-lg",
                                     method: :delete, data: {confirm: "Are you sure?"}
                                      %>
                                    <%   if x.mark == "undone" %>
                                  <%= link_to "Not Done", support_path(x.id),{class: "btn btn-info btn-lg"} %>
                                  <% else %>
                                  <%= link_to "Done", support_path(x.id),{class: "btn btn-info btn-lg"} %>
                                  <% end %>
 </td>
</tr>
</tbody>
<% end %>
</table>
<div class="digg_pagination">
<%= paginate @supports %>
</div>